### ISSUE TITLE
Uninstall binary netdata package?

### ISSUE THREAD

**Issue by mikeweilgart** [firehol/binary-packages#1]
After installing from `netdata-latest.gz.run`, it appears there is no automated way to uninstall.

If this is the case, can such a method please be added or created?  Or if there is already such a method, can it please be documented?  :)

If there is no automated uninstall method - what manual steps can I take to uninstall?

**Comment by mikeweilgart** [comment]
(I'm using RHEL 6, but of course the full solution should resolve this for every distro.)

**Comment by ktsaou** [comment]
Hi,

1. delete `/opt/netdata`
2. remove group `netdata` (`sudo groupdel netdata`)
3. remove user `netdata` (`sudo userdel netdata`)
4. remove `/etc/logrotate.d/netdata`
5. remove startup file, on systemd systems `/etc/systemd/system/netdata.service` on all other systems `/etc/init.d/netdata`

Actually, only the first is required. The others will become void when `/opt/netdata` is removed.

**Comment by londonowl1973** [comment]
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

**Comment by paulkatsoulakis** [comment]
https://docs.netdata.cloud/packaging/installer/uninstall/ -- kindly note that we are deprecating this repo, so please use netdata/netdata repository for any further inquiries
