### ISSUE TITLE
Check version of netdata installation from command line?

### ISSUE THREAD

**Issue by mikeweilgart** [firehol/binary-packages#2]
How to find out what version of netdata is installed?

All I've been able to find is:

```
# cat /opt/netdata/netdata-web-files/version.txt
16886efb0d56a244fafd73307544e58eae0ab9a5
#
```

But,

1. how to look this up to see its exact meaning (I can't find it in the commits through the GitHub UI), and
2. how to find a human-readable version number from the command line?

**Comment by ktsaou** [comment]
Something like this?

```sh
# netdata -version
netdata 1.7.0-179-gce9c10ae_rolling
```

**Comment by mikeweilgart** [comment]
This is fine, yes:

```
/opt/netdata/bin/netdata -version
```

What does version.txt reference?

**Comment by ktsaou** [comment]
> What does version.txt reference

It is the full git commit id of the last commt. The short version of the same appears in the version printed by binaries.

**Comment by mikeweilgart** [comment]
Thanks!  I didn't see the commit ID anywhere in changelog, release notes, or release tags in GitHub, but by going directly to https://github.com/firehol/netdata/commit/16886efb0d56a244fafd73307544e58eae0ab9a5 I found it.
