### ISSUE TITLE
How to install netdata without starting it?

### ISSUE THREAD

**Issue by Wing924** [firehol/binary-packages#3]
We can do `./netdata-installer.sh --dont-wait --dont-start-it` to only install but not starting netdata from source.
How can we do it from binary-package?

**Comment by ktsaou** [comment]
The `--dont-wait` option works on the static installer too.
Unfortunately `--dont-start-it` is not supported by the static installer. Why do you need it?

**Comment by Wing924** [comment]
@ktsaou 
I use chef to setup all my servers.
I need to do following things:
1.  install  netdata
2. setup  configs
3. start netdata service

I don't  want  it starts before configs.

**Comment by ktsaou** [comment]
Making  a PR now.

**Comment by ktsaou** [comment]
done, ready to run it:

```sh
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --dont-start-it
```

**Comment by Wing924** [comment]
it works! Thank you.
