### ISSUE TITLE
ipmi plugin for binary package

### ISSUE THREAD

**Issue by clinta** [firehol/binary-packages#5]
Is there a way to build the binary packages with [IMPI monitoring](https://github.com/firehol/netdata/wiki/monitoring-IPMI) support?

I've tried doing it myself by running build-latest.sh on a system that has libipmimonitoring-dev installed, and while IPMI showed up after the build script installed netdata from source, once I remove that and installed the .run file it generated there was no ipmi monitoring.

**Comment by ktsaou** [comment]
Sorry for the long delay:
I tried it, but failed: https://github.com/firehol/netdata/issues/3711

**Comment by paulkatsoulakis** [comment]
we have work in progress with ipmi, kindly refer to netdata/netdata project for any further information as this repo is deprecated now
