### ISSUE TITLE
Openldap deployment on existing server

### ISSUE THREAD

**Issue by vnr7** [firehol/binary-packages#6]
Hello,

I have configured Openldap directory server in my environment with a test client server running Linux OS to evaluate logins and authentications. However, now I'm looking to bring some existing servers in my non-prod environment which are running Linux OS and on which users are created locally on each server from before and their login authentication is also happening locally.

I need to configure the already existing servers as ldap client and migrate the users password sitting on the /etc/shadow file to my Openldap server so that their login is now authenticated from the directory server. Could someone please explain, how would I go about this process, what things do I need to do in order to achieve this?

Thanks

**Comment by ktsaou** [comment]
hm... are you sure this is the right repo for this?

**Comment by vnr7** [comment]
No, I'm not sure to be honest and I have not worked on this before so a complete beginner on this, if I'm at the wrong place could you please point me in the right direction.
